/**
 * Created by jhernandez on 4/10/15.
 */
var lang= {
    "en": {
        ERROR_MONGO_DB:"ERROR_MONGO_DB",
        USER_NOT_FOUND:"USER_NOT_FOUND",
        CANT_CRATE_USER:"CAN'T_CRATE_USER",
        CANT_GET_TAGS:"CAN'T_GET_TAGS",
        INVALID_TOKEN:"INVALID_TOKEN",
        DATA_MISSING:"DATA_MISSING",
        USER_EXIST_YET:"USER_EXIST_YET"
    },
    "es": {
        ERROR_MONGO_DB:"ERROR_MONGO_DB",
        USER_NOT_FOUND:"USUARIO_NO_ENCONTRADO",
        CANT_CRATE_USER:"IMPOSIBLE_CREAR_USUARIO",
        CANT_GET_TAGS:"IMPOSIBLE_OBTENER_TAGS",
        INVALID_TOKEN:"TOKEN_INVÁLIDO",
        DATA_MISSING:"FALTAN_DATOS",
        USER_EXIST_YET:"USUARIO_YA_EXISTE"
    }
};
module.exports=lang;